package com.spareparts.modules.auth.entity;

public enum ERole {
    ROLE_SYSTEM_ADMINISTRATOR,
    ROLE_PROCUREMENT_OFFICER,
    ROLE_SALES_STAFF,
    ROLE_SHOP_OWNER,
    ROLE_STORE_KEEPER,
    ROLE_COMPATIBILITY_MANAGER,
    ROLE_STORE_MANAGER
}
